spring.application.name=api

spring.mongodb.database=photobogota_demo

spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@pruebasdemo.fqcbxun.mongodb.net/photobogota_demo?retryWrites=true&w=majority&authSource=admin

# Expone el endpoint de health
management.endpoints.web.exposure.include=health

# Configura la base path del actuator para que esté bajo /api/v1/actuator
management.endpoints.web.base-path=/api/v1/actuator

# Muestra detalles (como el estado de la conexión a MongoDB)
management.endpoint.health.show-details=always

# Deshabilita el health check de MongoDB porqeu estamos usando uno personalizado
management.health.mongodb.enabled=false

# Configuración para la creación automática de índices en MongoDB
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
application.security.jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWp3dC1zZWNyZXQta2V5LWZvci1wb3RvYm9nb3Rh}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-expiration=604800000

# Configuracion de logging
logging.file.name=logs/photobogota-api.log

# Borra los logs antiguos después de 7 días o cuando el tamaño total de los logs alcance 500MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=500MB

# Formato de nombre para los archivos comprimidos de logs antiguos
logging.logback.rollingpolicy.file-name-pattern=logs/archived/photobogota.%d{yyyy-MM-dd}.%i.log.gz

# Configuración para mostrar colores en la consola 
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=photobogota123@gmail.com
spring.mail.password=jyqf aomx fcgr tqxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true