spring.application.name=api

spring.mongodb.database=photobogota-demo

spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@pruebasdemo.fqcbxun.mongodb.net/photobogota-demo?retryWrites=true&w=majority&authSource=admin

# Expone el endpoint de health
management.endpoints.web.exposure.include=health

# Muestra detalles (como el estado de la conexión a MongoDB)
management.endpoint.health.show-details=always

management.health.mongodb.enabled=false
